import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../../app/globals.css";
import { redirect } from "next/navigation";
import { getSessionUser } from "@/actions/user";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSessionUser();
  if (session) {
    redirect("/home");
  }
  return (
    <html lang="fr">
      <body className={`${montserrat.variable} account antialiased`}>
        {children}
      </body>
    </html>
  );
}
