import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../../app/globals.css";
import { redirect } from "next/navigation";
import { getSessionUser } from "@/actions/user";
import { Toaster } from "@/components/ui/sonner";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSessionUser();
  if (!session) {
    redirect("/login");
  }

  return (
    <html lang="fr">
      <body className={`${montserrat.variable} account antialiased`}>
        <div className="flex flex-col min-h-screen">
          <main className="">{children}</main>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
